import { withEnvelope, errorEnvelope } from '../utils/tool-result.js';
import type { ToolResult } from '../types.js';
import { getInstance } from '../config.js';
import { CollibraClient } from '../utils/collibra-client.js';

export const findWorkflowTasksTool = {
  name: 'find_workflow_tasks',
  description:
    'List open workflow tasks in a Collibra instance — the human to-do items generated by running workflows ' +
    '(e.g. "Approve Business Term"). Filter by title, business item (asset/domain/community UUID), or assignee user UUID. ' +
    'Use complete_workflow_task to finish a task.',
  inputSchema: {
    type: 'object',
    properties: {
      instance_name: {
        type: 'string',
        description: 'The name of the Collibra instance (as defined in config.json)',
      },
      title: {
        type: 'string',
        description: 'Optional: Filter by task title (partial match).',
      },
      business_item_id: {
        type: 'string',
        description: 'Optional: UUID of the asset/domain/community the tasks relate to.',
      },
      user_id: {
        type: 'string',
        description: 'Optional: UUID of a user — returns tasks assigned to (or claimable by) that user.',
      },
      limit: {
        type: 'number',
        description: 'Max results (default: 100, max: 1000).',
        default: 100,
      },
      offset: {
        type: 'number',
        description: 'Pagination offset (default: 0).',
        default: 0,
      },
    },
    required: ['instance_name'],
  },
  outputSchema: {
    type: 'object',
    description: 'Envelope with data.tasks: open workflow tasks matching the filter.',
    additionalProperties: true,
  },
};

export async function executeFindWorkflowTasks(args: any): Promise<ToolResult> {
  const { instance_name, title, business_item_id, user_id, limit = 100, offset = 0 } = args;

  try {
    const instance = getInstance(instance_name);
    const client = new CollibraClient(instance);

    const qp = new URLSearchParams({ limit: String(Math.min(limit, 1000)), offset: String(offset) });
    if (title) qp.set('title', title);
    if (business_item_id) qp.append('businessItemIds', business_item_id);
    if (user_id) qp.append('userIds', user_id);
    const resp = await client.restCall<any>(`/rest/2.0/workflowTasks?${qp.toString()}`);
    const results: any[] = resp.results || [];

    const tasks = results.map((t) => ({
      id: t.id,
      title: t.title ?? t.name ?? null,
      description: t.description ?? null,
      dueDate: t.dueDate ?? null,
      createdOn: t.createdOn ?? null,
      workflowDefinition: t.workflowDefinition ? { id: t.workflowDefinition.id, name: t.workflowDefinition.name } : null,
      businessItem: t.businessItemReference ?? t.businessItem ?? null,
      assignees: t.assignee ? [t.assignee] : t.assignees ?? [],
      candidateUsers: t.candidateUsers ?? undefined,
      formKey: t.formKey ?? null,
    }));

    return withEnvelope({
      instance: instance_name,
      operation: 'find_workflow_tasks',
      data: { count: tasks.length, total: resp.total ?? null, tasks },
      pagination: { offset, limit, ...(results.length === limit ? { nextOffset: offset + limit } : {}) },
      nextActions: tasks.slice(0, 1).map((t) => ({
        tool: 'complete_workflow_task',
        args: { instance_name, task_id: t.id },
        why: 'Preview the task form data and complete the task.',
      })),
    });
  } catch (error) {
    return errorEnvelope({
      instance: instance_name,
      operation: 'find_workflow_tasks',
      message: (error as Error).message,
    });
  }
}
